#!/bin/bash
set -e

[[ -n "${debug}" ]] && set -x

function exitwitherror() {
    echo "$1" >&2
    exit 1
}

# Preflight checks
[[ -z "$user" ]] && exitwitherror "Environment variable 'user' is not set"
[[ "$pwhash:${auth_keys}" == ":" ]] && exitwitherror "Environment variables 'pwhash' and 'auth_keys' are not set. Set either one"
[[ -z "$uid" ]] && exitwitherror "Environment variable 'uid' is not set"
[[ "$uid" -eq 0 ]] && exitwitherror "Environment variable 'uid' may not be 0"

# Add the user
getent passwd ${user} && {
    useradd --no-user-group --non-unique --uid ${uid} ${user}
    mkdir -p /home/${user}
    chown root:root /home/${user}
    chmod 755 /home/${user}
    
    # Add ssh keys if specified
    [[ -n "${auth_keys}" ]] && {
        mkdir /home/${user}/.ssh
        base64 -d <<< ${auth_keys} > /home/${user}/.ssh/authorized_keys
    }
    
    # Set password if specified
    [[ -n "${pwhash}" ]] && {
        chpasswd -e <<< "${user}:${pass}"
    } || {
        usermod -p "*" $user # disabled password
    }
}

# Generate unique ssh keys for this container, if needed
[[ ! -f /etc/ssh/ssh_host_ed25519_key ]] && ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
[[ ! -f /etc/ssh/ssh_host_rsa_key ]] && ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ''

getent passwd ${user} 2>/dev/null || {
    
}

exec /usr/sbin/sshd -D -e
